# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='题目')),
                ('category', models.CharField(choices=[('no-tec', '非技术'), ('tec', '技术')], max_length=20, verbose_name='分类')),
                ('limit', models.CharField(choices=[('public', '公开的'), ('private', '私有的')], max_length=10, verbose_name='权限')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('introduce', models.CharField(max_length=90, verbose_name='摘要')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='作者')),
            ],
        ),
    ]
