# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20190709_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='limit',
            field=models.CharField(max_length=10, verbose_name='权限'),
        ),
    ]
